FROM ruby:3.2.1
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

ENV DIR /back

WORKDIR /myapp
COPY ${DIR}/Gemfile /myapp/Gemfile
COPY ${DIR}/Gemfile.lock /myapp/Gemfile.lock
RUN bundle install
COPY ${DIR} /myapp

# Add a script to be executed every time the container starts.
COPY ${DIR}/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]
